name: CI

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest

        services:
          mysql:
            image: mysql
            env:
              MYSQL_ROOT_PASSWORD: password
              MYSQL_DATABASE: test
            ports:
              - 33306:3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 1

            - run: cp .env.ci .env

            - name: Install Chrome
              run: |
                cd ~
                sudo apt-get install libgbm1
                wget --quiet https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                sudo dpkg --install google-chrome-stable_current_amd64.deb
                cd -

            - name: Cache yarn
              uses: actions/cache@v1
              with:
                path: node_modules
                key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              run: |
                composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
                yarn install
                yarn run production

            - name: Generate Application Key
              run: php artisan key:generate

            - name: Setup config
              run: php artisan config:clear

            - name: Run Laravel Server
              run: php artisan serve &

            - name: Upgrade Chrome Driver
              run: php artisan dusk:chrome-driver

            - name: Start Chrome Driver
              run: ./vendor/laravel/dusk/bin/chromedriver-linux &

            - name: Run Dusk Tests
              run: composer tests
              env:
                APP_ENV: local
                APP_URL: "http://127.0.0.1:8000"
                DB_CONNECTION: mysql
                DB_DATABASE: test
                DB_PORT: ${{ job.services.mysql.ports[3306] }}
                DB_USER: root

            - name: Run cs-fixer
              run: composer dry-cs

